// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class AcceptedTokenSet extends ethereum.Event {
  get params(): AcceptedTokenSet__Params {
    return new AcceptedTokenSet__Params(this);
  }
}

export class AcceptedTokenSet__Params {
  _event: AcceptedTokenSet;

  constructor(event: AcceptedTokenSet) {
    this._event = event;
  }

  get _oldAcceptedToken(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newAcceptedToken(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class CommitteeSet extends ethereum.Event {
  get params(): CommitteeSet__Params {
    return new CommitteeSet__Params(this);
  }
}

export class CommitteeSet__Params {
  _event: CommitteeSet;

  constructor(event: CommitteeSet) {
    this._event = event;
  }

  get _oldCommittee(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newCommittee(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class FeesCollectorSet extends ethereum.Event {
  get params(): FeesCollectorSet__Params {
    return new FeesCollectorSet__Params(this);
  }
}

export class FeesCollectorSet__Params {
  _event: FeesCollectorSet;

  constructor(event: FeesCollectorSet) {
    this._event = event;
  }

  get _oldFeesCollector(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newFeesCollector(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class InitialItemValueSet extends ethereum.Event {
  get params(): InitialItemValueSet__Params {
    return new InitialItemValueSet__Params(this);
  }
}

export class InitialItemValueSet__Params {
  _event: InitialItemValueSet;

  constructor(event: InitialItemValueSet) {
    this._event = event;
  }

  get _oldInitialItemValue(): boolean {
    return this._event.parameters[0].value.toBoolean();
  }

  get _newInitialItemValue(): boolean {
    return this._event.parameters[1].value.toBoolean();
  }
}

export class InitialThirdPartyValueSet extends ethereum.Event {
  get params(): InitialThirdPartyValueSet__Params {
    return new InitialThirdPartyValueSet__Params(this);
  }
}

export class InitialThirdPartyValueSet__Params {
  _event: InitialThirdPartyValueSet;

  constructor(event: InitialThirdPartyValueSet) {
    this._event = event;
  }

  get _oldInitialThirdPartyValue(): boolean {
    return this._event.parameters[0].value.toBoolean();
  }

  get _newInitialThirdPartyValue(): boolean {
    return this._event.parameters[1].value.toBoolean();
  }
}

export class ItemAdded extends ethereum.Event {
  get params(): ItemAdded__Params {
    return new ItemAdded__Params(this);
  }
}

export class ItemAdded__Params {
  _event: ItemAdded;

  constructor(event: ItemAdded) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _itemId(): string {
    return this._event.parameters[1].value.toString();
  }

  get _metadata(): string {
    return this._event.parameters[2].value.toString();
  }

  get _value(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get _caller(): Address {
    return this._event.parameters[4].value.toAddress();
  }
}

export class ItemReviewed extends ethereum.Event {
  get params(): ItemReviewed__Params {
    return new ItemReviewed__Params(this);
  }
}

export class ItemReviewed__Params {
  _event: ItemReviewed;

  constructor(event: ItemReviewed) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _itemId(): string {
    return this._event.parameters[1].value.toString();
  }

  get _metadata(): string {
    return this._event.parameters[2].value.toString();
  }

  get _contentHash(): string {
    return this._event.parameters[3].value.toString();
  }

  get _value(): boolean {
    return this._event.parameters[4].value.toBoolean();
  }

  get _caller(): Address {
    return this._event.parameters[5].value.toAddress();
  }
}

export class ItemSlotPriceSet extends ethereum.Event {
  get params(): ItemSlotPriceSet__Params {
    return new ItemSlotPriceSet__Params(this);
  }
}

export class ItemSlotPriceSet__Params {
  _event: ItemSlotPriceSet;

  constructor(event: ItemSlotPriceSet) {
    this._event = event;
  }

  get _oldItemSlotPrice(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }

  get _newItemSlotPrice(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class ItemSlotsConsumed extends ethereum.Event {
  get params(): ItemSlotsConsumed__Params {
    return new ItemSlotsConsumed__Params(this);
  }
}

export class ItemSlotsConsumed__Params {
  _event: ItemSlotsConsumed;

  constructor(event: ItemSlotsConsumed) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _qty(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get _signer(): Address {
    return this._event.parameters[2].value.toAddress();
  }

  get _sender(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class ItemUpdated extends ethereum.Event {
  get params(): ItemUpdated__Params {
    return new ItemUpdated__Params(this);
  }
}

export class ItemUpdated__Params {
  _event: ItemUpdated;

  constructor(event: ItemUpdated) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _itemId(): string {
    return this._event.parameters[1].value.toString();
  }

  get _metadata(): string {
    return this._event.parameters[2].value.toString();
  }

  get _caller(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class MetaTransactionExecuted extends ethereum.Event {
  get params(): MetaTransactionExecuted__Params {
    return new MetaTransactionExecuted__Params(this);
  }
}

export class MetaTransactionExecuted__Params {
  _event: MetaTransactionExecuted;

  constructor(event: MetaTransactionExecuted) {
    this._event = event;
  }

  get userAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get relayerAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get functionSignature(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class OracleSet extends ethereum.Event {
  get params(): OracleSet__Params {
    return new OracleSet__Params(this);
  }
}

export class OracleSet__Params {
  _event: OracleSet;

  constructor(event: OracleSet) {
    this._event = event;
  }

  get _oldOracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newOracle(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class ThirdPartyAdded extends ethereum.Event {
  get params(): ThirdPartyAdded__Params {
    return new ThirdPartyAdded__Params(this);
  }
}

export class ThirdPartyAdded__Params {
  _event: ThirdPartyAdded;

  constructor(event: ThirdPartyAdded) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _metadata(): string {
    return this._event.parameters[1].value.toString();
  }

  get _resolver(): string {
    return this._event.parameters[2].value.toString();
  }

  get _isApproved(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get _managers(): Array<Address> {
    return this._event.parameters[4].value.toAddressArray();
  }

  get _itemSlots(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get _caller(): Address {
    return this._event.parameters[6].value.toAddress();
  }
}

export class ThirdPartyAgregatorSet extends ethereum.Event {
  get params(): ThirdPartyAgregatorSet__Params {
    return new ThirdPartyAgregatorSet__Params(this);
  }
}

export class ThirdPartyAgregatorSet__Params {
  _event: ThirdPartyAgregatorSet;

  constructor(event: ThirdPartyAgregatorSet) {
    this._event = event;
  }

  get _oldThirdPartyAgregator(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get _newThirdPartyAgregator(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class ThirdPartyItemSlotsBought extends ethereum.Event {
  get params(): ThirdPartyItemSlotsBought__Params {
    return new ThirdPartyItemSlotsBought__Params(this);
  }
}

export class ThirdPartyItemSlotsBought__Params {
  _event: ThirdPartyItemSlotsBought;

  constructor(event: ThirdPartyItemSlotsBought) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _price(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get _value(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _caller(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class ThirdPartyReviewed extends ethereum.Event {
  get params(): ThirdPartyReviewed__Params {
    return new ThirdPartyReviewed__Params(this);
  }
}

export class ThirdPartyReviewed__Params {
  _event: ThirdPartyReviewed;

  constructor(event: ThirdPartyReviewed) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _value(): boolean {
    return this._event.parameters[1].value.toBoolean();
  }

  get _caller(): Address {
    return this._event.parameters[2].value.toAddress();
  }
}

export class ThirdPartyReviewedWithRoot extends ethereum.Event {
  get params(): ThirdPartyReviewedWithRoot__Params {
    return new ThirdPartyReviewedWithRoot__Params(this);
  }
}

export class ThirdPartyReviewedWithRoot__Params {
  _event: ThirdPartyReviewedWithRoot;

  constructor(event: ThirdPartyReviewedWithRoot) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _root(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get _isApproved(): boolean {
    return this._event.parameters[2].value.toBoolean();
  }

  get _sender(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class ThirdPartyRuleAdded extends ethereum.Event {
  get params(): ThirdPartyRuleAdded__Params {
    return new ThirdPartyRuleAdded__Params(this);
  }
}

export class ThirdPartyRuleAdded__Params {
  _event: ThirdPartyRuleAdded;

  constructor(event: ThirdPartyRuleAdded) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _rule(): string {
    return this._event.parameters[1].value.toString();
  }

  get _value(): boolean {
    return this._event.parameters[2].value.toBoolean();
  }

  get _sender(): Address {
    return this._event.parameters[3].value.toAddress();
  }
}

export class ThirdPartyUpdated extends ethereum.Event {
  get params(): ThirdPartyUpdated__Params {
    return new ThirdPartyUpdated__Params(this);
  }
}

export class ThirdPartyUpdated__Params {
  _event: ThirdPartyUpdated;

  constructor(event: ThirdPartyUpdated) {
    this._event = event;
  }

  get _thirdPartyId(): string {
    return this._event.parameters[0].value.toString();
  }

  get _metadata(): string {
    return this._event.parameters[1].value.toString();
  }

  get _resolver(): string {
    return this._event.parameters[2].value.toString();
  }

  get _managers(): Array<Address> {
    return this._event.parameters[3].value.toAddressArray();
  }

  get _managerValues(): Array<boolean> {
    return this._event.parameters[4].value.toBooleanArray();
  }

  get _itemSlots(): BigInt {
    return this._event.parameters[5].value.toBigInt();
  }

  get _caller(): Address {
    return this._event.parameters[6].value.toAddress();
  }
}

export class ThirdPartyRegistry__itemsByIdResultValue0Struct extends ethereum.Tuple {
  get metadata(): string {
    return this[0].toString();
  }

  get contentHash(): string {
    return this[1].toString();
  }

  get isApproved(): boolean {
    return this[2].toBoolean();
  }

  get registered(): BigInt {
    return this[3].toBigInt();
  }
}

export class ThirdPartyRegistry__thirdPartiesResult {
  value0: boolean;
  value1: Bytes;
  value2: BigInt;
  value3: BigInt;
  value4: BigInt;
  value5: string;
  value6: string;

  constructor(
    value0: boolean,
    value1: Bytes,
    value2: BigInt,
    value3: BigInt,
    value4: BigInt,
    value5: string,
    value6: string
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
    this.value6 = value6;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromBoolean(this.value0));
    map.set("value1", ethereum.Value.fromFixedBytes(this.value1));
    map.set("value2", ethereum.Value.fromUnsignedBigInt(this.value2));
    map.set("value3", ethereum.Value.fromUnsignedBigInt(this.value3));
    map.set("value4", ethereum.Value.fromUnsignedBigInt(this.value4));
    map.set("value5", ethereum.Value.fromString(this.value5));
    map.set("value6", ethereum.Value.fromString(this.value6));
    return map;
  }
}

export class ThirdPartyRegistry extends ethereum.SmartContract {
  static bind(address: Address): ThirdPartyRegistry {
    return new ThirdPartyRegistry("ThirdPartyRegistry", address);
  }

  acceptedToken(): Address {
    let result = super.call("acceptedToken", "acceptedToken():(address)", []);

    return result[0].toAddress();
  }

  try_acceptedToken(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "acceptedToken",
      "acceptedToken():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  committee(): Address {
    let result = super.call("committee", "committee():(address)", []);

    return result[0].toAddress();
  }

  try_committee(): ethereum.CallResult<Address> {
    let result = super.tryCall("committee", "committee():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  domainSeparator(): Bytes {
    let result = super.call(
      "domainSeparator",
      "domainSeparator():(bytes32)",
      []
    );

    return result[0].toBytes();
  }

  try_domainSeparator(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "domainSeparator",
      "domainSeparator():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  feesCollector(): Address {
    let result = super.call("feesCollector", "feesCollector():(address)", []);

    return result[0].toAddress();
  }

  try_feesCollector(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "feesCollector",
      "feesCollector():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getChainId(): BigInt {
    let result = super.call("getChainId", "getChainId():(uint256)", []);

    return result[0].toBigInt();
  }

  try_getChainId(): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getChainId", "getChainId():(uint256)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getNonce(user: Address): BigInt {
    let result = super.call("getNonce", "getNonce(address):(uint256)", [
      ethereum.Value.fromAddress(user)
    ]);

    return result[0].toBigInt();
  }

  try_getNonce(user: Address): ethereum.CallResult<BigInt> {
    let result = super.tryCall("getNonce", "getNonce(address):(uint256)", [
      ethereum.Value.fromAddress(user)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  getRuleValue(_thirdPartyId: string, _rule: string): boolean {
    let result = super.call(
      "getRuleValue",
      "getRuleValue(string,string):(bool)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromString(_rule)
      ]
    );

    return result[0].toBoolean();
  }

  try_getRuleValue(
    _thirdPartyId: string,
    _rule: string
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "getRuleValue",
      "getRuleValue(string,string):(bool)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromString(_rule)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  initialItemValue(): boolean {
    let result = super.call(
      "initialItemValue",
      "initialItemValue():(bool)",
      []
    );

    return result[0].toBoolean();
  }

  try_initialItemValue(): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "initialItemValue",
      "initialItemValue():(bool)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  initialThirdPartyValue(): boolean {
    let result = super.call(
      "initialThirdPartyValue",
      "initialThirdPartyValue():(bool)",
      []
    );

    return result[0].toBoolean();
  }

  try_initialThirdPartyValue(): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "initialThirdPartyValue",
      "initialThirdPartyValue():(bool)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  isThirdPartyManager(_thirdPartyId: string, _manager: Address): boolean {
    let result = super.call(
      "isThirdPartyManager",
      "isThirdPartyManager(string,address):(bool)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromAddress(_manager)
      ]
    );

    return result[0].toBoolean();
  }

  try_isThirdPartyManager(
    _thirdPartyId: string,
    _manager: Address
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "isThirdPartyManager",
      "isThirdPartyManager(string,address):(bool)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromAddress(_manager)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  itemIdByIndex(_thirdPartyId: string, _index: BigInt): string {
    let result = super.call(
      "itemIdByIndex",
      "itemIdByIndex(string,uint256):(string)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromUnsignedBigInt(_index)
      ]
    );

    return result[0].toString();
  }

  try_itemIdByIndex(
    _thirdPartyId: string,
    _index: BigInt
  ): ethereum.CallResult<string> {
    let result = super.tryCall(
      "itemIdByIndex",
      "itemIdByIndex(string,uint256):(string)",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromUnsignedBigInt(_index)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  itemSlotPrice(): BigInt {
    let result = super.call("itemSlotPrice", "itemSlotPrice():(uint256)", []);

    return result[0].toBigInt();
  }

  try_itemSlotPrice(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "itemSlotPrice",
      "itemSlotPrice():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  itemsById(
    _thirdPartyId: string,
    _itemId: string
  ): ThirdPartyRegistry__itemsByIdResultValue0Struct {
    let result = super.call(
      "itemsById",
      "itemsById(string,string):((string,string,bool,uint256))",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromString(_itemId)
      ]
    );

    return changetype<ThirdPartyRegistry__itemsByIdResultValue0Struct>(
      result[0].toTuple()
    );
  }

  try_itemsById(
    _thirdPartyId: string,
    _itemId: string
  ): ethereum.CallResult<ThirdPartyRegistry__itemsByIdResultValue0Struct> {
    let result = super.tryCall(
      "itemsById",
      "itemsById(string,string):((string,string,bool,uint256))",
      [
        ethereum.Value.fromString(_thirdPartyId),
        ethereum.Value.fromString(_itemId)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      changetype<ThirdPartyRegistry__itemsByIdResultValue0Struct>(
        value[0].toTuple()
      )
    );
  }

  itemsCount(_thirdPartyId: string): BigInt {
    let result = super.call("itemsCount", "itemsCount(string):(uint256)", [
      ethereum.Value.fromString(_thirdPartyId)
    ]);

    return result[0].toBigInt();
  }

  try_itemsCount(_thirdPartyId: string): ethereum.CallResult<BigInt> {
    let result = super.tryCall("itemsCount", "itemsCount(string):(uint256)", [
      ethereum.Value.fromString(_thirdPartyId)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  oracle(): Address {
    let result = super.call("oracle", "oracle():(address)", []);

    return result[0].toAddress();
  }

  try_oracle(): ethereum.CallResult<Address> {
    let result = super.tryCall("oracle", "oracle():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  thirdParties(param0: string): ThirdPartyRegistry__thirdPartiesResult {
    let result = super.call(
      "thirdParties",
      "thirdParties(string):(bool,bytes32,uint256,uint256,uint256,string,string)",
      [ethereum.Value.fromString(param0)]
    );

    return new ThirdPartyRegistry__thirdPartiesResult(
      result[0].toBoolean(),
      result[1].toBytes(),
      result[2].toBigInt(),
      result[3].toBigInt(),
      result[4].toBigInt(),
      result[5].toString(),
      result[6].toString()
    );
  }

  try_thirdParties(
    param0: string
  ): ethereum.CallResult<ThirdPartyRegistry__thirdPartiesResult> {
    let result = super.tryCall(
      "thirdParties",
      "thirdParties(string):(bool,bytes32,uint256,uint256,uint256,string,string)",
      [ethereum.Value.fromString(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new ThirdPartyRegistry__thirdPartiesResult(
        value[0].toBoolean(),
        value[1].toBytes(),
        value[2].toBigInt(),
        value[3].toBigInt(),
        value[4].toBigInt(),
        value[5].toString(),
        value[6].toString()
      )
    );
  }

  thirdPartiesCount(): BigInt {
    let result = super.call(
      "thirdPartiesCount",
      "thirdPartiesCount():(uint256)",
      []
    );

    return result[0].toBigInt();
  }

  try_thirdPartiesCount(): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "thirdPartiesCount",
      "thirdPartiesCount():(uint256)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  thirdPartyAgregator(): Address {
    let result = super.call(
      "thirdPartyAgregator",
      "thirdPartyAgregator():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_thirdPartyAgregator(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "thirdPartyAgregator",
      "thirdPartyAgregator():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  thirdPartyIds(param0: BigInt): string {
    let result = super.call(
      "thirdPartyIds",
      "thirdPartyIds(uint256):(string)",
      [ethereum.Value.fromUnsignedBigInt(param0)]
    );

    return result[0].toString();
  }

  try_thirdPartyIds(param0: BigInt): ethereum.CallResult<string> {
    let result = super.tryCall(
      "thirdPartyIds",
      "thirdPartyIds(uint256):(string)",
      [ethereum.Value.fromUnsignedBigInt(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _owner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _thirdPartyAgregator(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _feesCollector(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _committee(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get _acceptedToken(): Address {
    return this._call.inputValues[4].value.toAddress();
  }

  get _oracle(): Address {
    return this._call.inputValues[5].value.toAddress();
  }

  get _itemSlotPrice(): BigInt {
    return this._call.inputValues[6].value.toBigInt();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class AddItemsCall extends ethereum.Call {
  get inputs(): AddItemsCall__Inputs {
    return new AddItemsCall__Inputs(this);
  }

  get outputs(): AddItemsCall__Outputs {
    return new AddItemsCall__Outputs(this);
  }
}

export class AddItemsCall__Inputs {
  _call: AddItemsCall;

  constructor(call: AddItemsCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _items(): Array<AddItemsCall_itemsStruct> {
    return this._call.inputValues[1].value.toTupleArray<
      AddItemsCall_itemsStruct
    >();
  }
}

export class AddItemsCall__Outputs {
  _call: AddItemsCall;

  constructor(call: AddItemsCall) {
    this._call = call;
  }
}

export class AddItemsCall_itemsStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get metadata(): string {
    return this[1].toString();
  }
}

export class AddThirdPartiesCall extends ethereum.Call {
  get inputs(): AddThirdPartiesCall__Inputs {
    return new AddThirdPartiesCall__Inputs(this);
  }

  get outputs(): AddThirdPartiesCall__Outputs {
    return new AddThirdPartiesCall__Outputs(this);
  }
}

export class AddThirdPartiesCall__Inputs {
  _call: AddThirdPartiesCall;

  constructor(call: AddThirdPartiesCall) {
    this._call = call;
  }

  get _thirdParties(): Array<AddThirdPartiesCall_thirdPartiesStruct> {
    return this._call.inputValues[0].value.toTupleArray<
      AddThirdPartiesCall_thirdPartiesStruct
    >();
  }
}

export class AddThirdPartiesCall__Outputs {
  _call: AddThirdPartiesCall;

  constructor(call: AddThirdPartiesCall) {
    this._call = call;
  }
}

export class AddThirdPartiesCall_thirdPartiesStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get metadata(): string {
    return this[1].toString();
  }

  get resolver(): string {
    return this[2].toString();
  }

  get managers(): Array<Address> {
    return this[3].toAddressArray();
  }

  get managerValues(): Array<boolean> {
    return this[4].toBooleanArray();
  }

  get slots(): BigInt {
    return this[5].toBigInt();
  }
}

export class BuyItemSlotsCall extends ethereum.Call {
  get inputs(): BuyItemSlotsCall__Inputs {
    return new BuyItemSlotsCall__Inputs(this);
  }

  get outputs(): BuyItemSlotsCall__Outputs {
    return new BuyItemSlotsCall__Outputs(this);
  }
}

export class BuyItemSlotsCall__Inputs {
  _call: BuyItemSlotsCall;

  constructor(call: BuyItemSlotsCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _qty(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }

  get _maxPrice(): BigInt {
    return this._call.inputValues[2].value.toBigInt();
  }
}

export class BuyItemSlotsCall__Outputs {
  _call: BuyItemSlotsCall;

  constructor(call: BuyItemSlotsCall) {
    this._call = call;
  }
}

export class ConsumeSlotsCall extends ethereum.Call {
  get inputs(): ConsumeSlotsCall__Inputs {
    return new ConsumeSlotsCall__Inputs(this);
  }

  get outputs(): ConsumeSlotsCall__Outputs {
    return new ConsumeSlotsCall__Outputs(this);
  }
}

export class ConsumeSlotsCall__Inputs {
  _call: ConsumeSlotsCall;

  constructor(call: ConsumeSlotsCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _consumeSlotsParams(): Array<ConsumeSlotsCall_consumeSlotsParamsStruct> {
    return this._call.inputValues[1].value.toTupleArray<
      ConsumeSlotsCall_consumeSlotsParamsStruct
    >();
  }
}

export class ConsumeSlotsCall__Outputs {
  _call: ConsumeSlotsCall;

  constructor(call: ConsumeSlotsCall) {
    this._call = call;
  }
}

export class ConsumeSlotsCall_consumeSlotsParamsStruct extends ethereum.Tuple {
  get qty(): BigInt {
    return this[0].toBigInt();
  }

  get salt(): Bytes {
    return this[1].toBytes();
  }

  get sigR(): Bytes {
    return this[2].toBytes();
  }

  get sigS(): Bytes {
    return this[3].toBytes();
  }

  get sigV(): i32 {
    return this[4].toI32();
  }
}

export class ExecuteMetaTransactionCall extends ethereum.Call {
  get inputs(): ExecuteMetaTransactionCall__Inputs {
    return new ExecuteMetaTransactionCall__Inputs(this);
  }

  get outputs(): ExecuteMetaTransactionCall__Outputs {
    return new ExecuteMetaTransactionCall__Outputs(this);
  }
}

export class ExecuteMetaTransactionCall__Inputs {
  _call: ExecuteMetaTransactionCall;

  constructor(call: ExecuteMetaTransactionCall) {
    this._call = call;
  }

  get userAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get functionSignature(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get sigR(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }

  get sigS(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }

  get sigV(): i32 {
    return this._call.inputValues[4].value.toI32();
  }
}

export class ExecuteMetaTransactionCall__Outputs {
  _call: ExecuteMetaTransactionCall;

  constructor(call: ExecuteMetaTransactionCall) {
    this._call = call;
  }

  get value0(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class ReviewThirdPartiesCall extends ethereum.Call {
  get inputs(): ReviewThirdPartiesCall__Inputs {
    return new ReviewThirdPartiesCall__Inputs(this);
  }

  get outputs(): ReviewThirdPartiesCall__Outputs {
    return new ReviewThirdPartiesCall__Outputs(this);
  }
}

export class ReviewThirdPartiesCall__Inputs {
  _call: ReviewThirdPartiesCall;

  constructor(call: ReviewThirdPartiesCall) {
    this._call = call;
  }

  get _thirdParties(): Array<ReviewThirdPartiesCall_thirdPartiesStruct> {
    return this._call.inputValues[0].value.toTupleArray<
      ReviewThirdPartiesCall_thirdPartiesStruct
    >();
  }
}

export class ReviewThirdPartiesCall__Outputs {
  _call: ReviewThirdPartiesCall;

  constructor(call: ReviewThirdPartiesCall) {
    this._call = call;
  }
}

export class ReviewThirdPartiesCall_thirdPartiesStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get value(): boolean {
    return this[1].toBoolean();
  }

  get items(): Array<ReviewThirdPartiesCall_thirdPartiesItemsStruct> {
    return this[2].toTupleArray<
      ReviewThirdPartiesCall_thirdPartiesItemsStruct
    >();
  }
}

export class ReviewThirdPartiesCall_thirdPartiesItemsStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get metadata(): string {
    return this[1].toString();
  }

  get contentHash(): string {
    return this[2].toString();
  }

  get value(): boolean {
    return this[3].toBoolean();
  }
}

export class ReviewThirdPartyWithRootCall extends ethereum.Call {
  get inputs(): ReviewThirdPartyWithRootCall__Inputs {
    return new ReviewThirdPartyWithRootCall__Inputs(this);
  }

  get outputs(): ReviewThirdPartyWithRootCall__Outputs {
    return new ReviewThirdPartyWithRootCall__Outputs(this);
  }
}

export class ReviewThirdPartyWithRootCall__Inputs {
  _call: ReviewThirdPartyWithRootCall;

  constructor(call: ReviewThirdPartyWithRootCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _root(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get _consumeSlotsParams(): Array<
    ReviewThirdPartyWithRootCall_consumeSlotsParamsStruct
  > {
    return this._call.inputValues[2].value.toTupleArray<
      ReviewThirdPartyWithRootCall_consumeSlotsParamsStruct
    >();
  }
}

export class ReviewThirdPartyWithRootCall__Outputs {
  _call: ReviewThirdPartyWithRootCall;

  constructor(call: ReviewThirdPartyWithRootCall) {
    this._call = call;
  }
}

export class ReviewThirdPartyWithRootCall_consumeSlotsParamsStruct extends ethereum.Tuple {
  get qty(): BigInt {
    return this[0].toBigInt();
  }

  get salt(): Bytes {
    return this[1].toBytes();
  }

  get sigR(): Bytes {
    return this[2].toBytes();
  }

  get sigS(): Bytes {
    return this[3].toBytes();
  }

  get sigV(): i32 {
    return this[4].toI32();
  }
}

export class SetAcceptedTokenCall extends ethereum.Call {
  get inputs(): SetAcceptedTokenCall__Inputs {
    return new SetAcceptedTokenCall__Inputs(this);
  }

  get outputs(): SetAcceptedTokenCall__Outputs {
    return new SetAcceptedTokenCall__Outputs(this);
  }
}

export class SetAcceptedTokenCall__Inputs {
  _call: SetAcceptedTokenCall;

  constructor(call: SetAcceptedTokenCall) {
    this._call = call;
  }

  get _newAcceptedToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetAcceptedTokenCall__Outputs {
  _call: SetAcceptedTokenCall;

  constructor(call: SetAcceptedTokenCall) {
    this._call = call;
  }
}

export class SetCommitteeCall extends ethereum.Call {
  get inputs(): SetCommitteeCall__Inputs {
    return new SetCommitteeCall__Inputs(this);
  }

  get outputs(): SetCommitteeCall__Outputs {
    return new SetCommitteeCall__Outputs(this);
  }
}

export class SetCommitteeCall__Inputs {
  _call: SetCommitteeCall;

  constructor(call: SetCommitteeCall) {
    this._call = call;
  }

  get _newCommittee(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetCommitteeCall__Outputs {
  _call: SetCommitteeCall;

  constructor(call: SetCommitteeCall) {
    this._call = call;
  }
}

export class SetFeesCollectorCall extends ethereum.Call {
  get inputs(): SetFeesCollectorCall__Inputs {
    return new SetFeesCollectorCall__Inputs(this);
  }

  get outputs(): SetFeesCollectorCall__Outputs {
    return new SetFeesCollectorCall__Outputs(this);
  }
}

export class SetFeesCollectorCall__Inputs {
  _call: SetFeesCollectorCall;

  constructor(call: SetFeesCollectorCall) {
    this._call = call;
  }

  get _newFeesCollector(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetFeesCollectorCall__Outputs {
  _call: SetFeesCollectorCall;

  constructor(call: SetFeesCollectorCall) {
    this._call = call;
  }
}

export class SetInitialItemValueCall extends ethereum.Call {
  get inputs(): SetInitialItemValueCall__Inputs {
    return new SetInitialItemValueCall__Inputs(this);
  }

  get outputs(): SetInitialItemValueCall__Outputs {
    return new SetInitialItemValueCall__Outputs(this);
  }
}

export class SetInitialItemValueCall__Inputs {
  _call: SetInitialItemValueCall;

  constructor(call: SetInitialItemValueCall) {
    this._call = call;
  }

  get _newinitialItemValue(): boolean {
    return this._call.inputValues[0].value.toBoolean();
  }
}

export class SetInitialItemValueCall__Outputs {
  _call: SetInitialItemValueCall;

  constructor(call: SetInitialItemValueCall) {
    this._call = call;
  }
}

export class SetInitialThirdPartyValueCall extends ethereum.Call {
  get inputs(): SetInitialThirdPartyValueCall__Inputs {
    return new SetInitialThirdPartyValueCall__Inputs(this);
  }

  get outputs(): SetInitialThirdPartyValueCall__Outputs {
    return new SetInitialThirdPartyValueCall__Outputs(this);
  }
}

export class SetInitialThirdPartyValueCall__Inputs {
  _call: SetInitialThirdPartyValueCall;

  constructor(call: SetInitialThirdPartyValueCall) {
    this._call = call;
  }

  get _newinitialThirdPartyValue(): boolean {
    return this._call.inputValues[0].value.toBoolean();
  }
}

export class SetInitialThirdPartyValueCall__Outputs {
  _call: SetInitialThirdPartyValueCall;

  constructor(call: SetInitialThirdPartyValueCall) {
    this._call = call;
  }
}

export class SetItemSlotPriceCall extends ethereum.Call {
  get inputs(): SetItemSlotPriceCall__Inputs {
    return new SetItemSlotPriceCall__Inputs(this);
  }

  get outputs(): SetItemSlotPriceCall__Outputs {
    return new SetItemSlotPriceCall__Outputs(this);
  }
}

export class SetItemSlotPriceCall__Inputs {
  _call: SetItemSlotPriceCall;

  constructor(call: SetItemSlotPriceCall) {
    this._call = call;
  }

  get _newItemSlotPrice(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class SetItemSlotPriceCall__Outputs {
  _call: SetItemSlotPriceCall;

  constructor(call: SetItemSlotPriceCall) {
    this._call = call;
  }
}

export class SetOracleCall extends ethereum.Call {
  get inputs(): SetOracleCall__Inputs {
    return new SetOracleCall__Inputs(this);
  }

  get outputs(): SetOracleCall__Outputs {
    return new SetOracleCall__Outputs(this);
  }
}

export class SetOracleCall__Inputs {
  _call: SetOracleCall;

  constructor(call: SetOracleCall) {
    this._call = call;
  }

  get _newOracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetOracleCall__Outputs {
  _call: SetOracleCall;

  constructor(call: SetOracleCall) {
    this._call = call;
  }
}

export class SetRulesCall extends ethereum.Call {
  get inputs(): SetRulesCall__Inputs {
    return new SetRulesCall__Inputs(this);
  }

  get outputs(): SetRulesCall__Outputs {
    return new SetRulesCall__Outputs(this);
  }
}

export class SetRulesCall__Inputs {
  _call: SetRulesCall;

  constructor(call: SetRulesCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _rules(): Array<string> {
    return this._call.inputValues[1].value.toStringArray();
  }

  get _values(): Array<boolean> {
    return this._call.inputValues[2].value.toBooleanArray();
  }
}

export class SetRulesCall__Outputs {
  _call: SetRulesCall;

  constructor(call: SetRulesCall) {
    this._call = call;
  }
}

export class SetThirdPartyAgregatorCall extends ethereum.Call {
  get inputs(): SetThirdPartyAgregatorCall__Inputs {
    return new SetThirdPartyAgregatorCall__Inputs(this);
  }

  get outputs(): SetThirdPartyAgregatorCall__Outputs {
    return new SetThirdPartyAgregatorCall__Outputs(this);
  }
}

export class SetThirdPartyAgregatorCall__Inputs {
  _call: SetThirdPartyAgregatorCall;

  constructor(call: SetThirdPartyAgregatorCall) {
    this._call = call;
  }

  get _newThirdPartyAgregator(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetThirdPartyAgregatorCall__Outputs {
  _call: SetThirdPartyAgregatorCall;

  constructor(call: SetThirdPartyAgregatorCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class UpdateItemsCall extends ethereum.Call {
  get inputs(): UpdateItemsCall__Inputs {
    return new UpdateItemsCall__Inputs(this);
  }

  get outputs(): UpdateItemsCall__Outputs {
    return new UpdateItemsCall__Outputs(this);
  }
}

export class UpdateItemsCall__Inputs {
  _call: UpdateItemsCall;

  constructor(call: UpdateItemsCall) {
    this._call = call;
  }

  get _thirdPartyId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _items(): Array<UpdateItemsCall_itemsStruct> {
    return this._call.inputValues[1].value.toTupleArray<
      UpdateItemsCall_itemsStruct
    >();
  }
}

export class UpdateItemsCall__Outputs {
  _call: UpdateItemsCall;

  constructor(call: UpdateItemsCall) {
    this._call = call;
  }
}

export class UpdateItemsCall_itemsStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get metadata(): string {
    return this[1].toString();
  }
}

export class UpdateThirdPartiesCall extends ethereum.Call {
  get inputs(): UpdateThirdPartiesCall__Inputs {
    return new UpdateThirdPartiesCall__Inputs(this);
  }

  get outputs(): UpdateThirdPartiesCall__Outputs {
    return new UpdateThirdPartiesCall__Outputs(this);
  }
}

export class UpdateThirdPartiesCall__Inputs {
  _call: UpdateThirdPartiesCall;

  constructor(call: UpdateThirdPartiesCall) {
    this._call = call;
  }

  get _thirdParties(): Array<UpdateThirdPartiesCall_thirdPartiesStruct> {
    return this._call.inputValues[0].value.toTupleArray<
      UpdateThirdPartiesCall_thirdPartiesStruct
    >();
  }
}

export class UpdateThirdPartiesCall__Outputs {
  _call: UpdateThirdPartiesCall;

  constructor(call: UpdateThirdPartiesCall) {
    this._call = call;
  }
}

export class UpdateThirdPartiesCall_thirdPartiesStruct extends ethereum.Tuple {
  get id(): string {
    return this[0].toString();
  }

  get metadata(): string {
    return this[1].toString();
  }

  get resolver(): string {
    return this[2].toString();
  }

  get managers(): Array<Address> {
    return this[3].toAddressArray();
  }

  get managerValues(): Array<boolean> {
    return this[4].toBooleanArray();
  }

  get slots(): BigInt {
    return this[5].toBigInt();
  }
}
