export let Categories = new Array<string>()
Categories.push('eyebrows')
Categories.push('eyes')
Categories.push('facial_hair')
Categories.push('hair')
Categories.push('mouth')
Categories.push('upper_body')
Categories.push('lower_body')
Categories.push('feet')
Categories.push('earring')
Categories.push('eyewear')
Categories.push('hat')
Categories.push('mask')
Categories.push('tiara')
Categories.push('top_head')

export let BodyShapes = new Array<string>()
BodyShapes.push('BaseFemale')
BodyShapes.push('BaseMale')
